//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace YC.Students
{
    public partial interface IStudentsStore : IDomainService //auto-generated
    {
        //IStudentRepository Student { get; }
        //IGroupRepository Group { get; }
    }
    public partial class StudentsStore : DomainService, IStudentsStore //auto-generated
    {
        //public IStudentRepository Student => this.LazyServiceProvider.LazyGetRequiredService<IStudentRepository>();
        //public IGroupRepository Group => this.LazyServiceProvider.LazyGetRequiredService<IGroupRepository>();
    }
}
