//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;
using YC.Controllers;

namespace YC.Students
{
    [Area("yc")]
    [RemoteService(true)]
    [ControllerName("YC.Students(yc)")]
    [Route("api/yc/students")]
    public partial class StudentsApi : YCController , IStudentsApi //auto-generated
    {

        protected IStudentCrudAppService StudentCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IStudentCrudAppService>();

        protected IGroupCrudAppService GroupCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IGroupCrudAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
