//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace YC.Students
{
    public partial interface IStudentCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<YC.Students.Dtos.StudentWithDetailsDto, Guid, YC.Students.Dtos.StudentGetListDto, YC.Students.Dtos.StudentCreateDto, YC.Students.Dtos.StudentUpdateDto>
    {

    }
}
