//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;

namespace YC.Students
{
    public partial class EfCoreGroupRepository : 
        EfCoreRepository<YC.EntityFrameworkCore.IYCDbContext,YC.Students.Group,Guid>,
        IGroupRepository
    {
        public EfCoreGroupRepository(IDbContextProvider<YC.EntityFrameworkCore.IYCDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<YC.Students.Group>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
}
