//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace YC.Students.Dtos
{
    public partial class GroupAutoMapperProfile : Profile
    {
        public GroupAutoMapperProfile()
        {
            CreateMap<YC.Students.Group, GroupDto>()
            .ReverseMap();
        
            CreateMap<GroupCreateDto, YC.Students.Group>();
        
            CreateMap<GroupUpdateDto, YC.Students.Group>();
        
            CreateMap<YC.Students.Group, GroupWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
