//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace YC.Students.Dtos
{
    public partial class MetaData
    {
        public StudentPrimaryKeyDto StudentPrimaryKeyDto => new StudentPrimaryKeyDto();
        public StudentDto StudentDto => new StudentDto();
        public StudentCreateDto StudentCreateDto => new StudentCreateDto();
        public StudentUpdateDto StudentUpdateDto => new StudentUpdateDto();
        public StudentGetListDto StudentGetListDto => new StudentGetListDto();
        public StudentWithDetailsDto StudentWithDetailsDto => new StudentWithDetailsDto();
    }

    public partial class StudentPrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class StudentDto : Volo.Abp.Application.Dtos.AuditedEntityDto<Guid>
    {
        public virtual string Name { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual System.Guid GroupId { get; set; }

    }

    public partial class StudentCreateDto
    {
        public virtual string Name { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual System.Guid GroupId { get; set; }

    }

    public partial class StudentUpdateDto
    {
        public virtual string Name { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual System.Guid GroupId { get; set; }

    }

    public partial class StudentGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class StudentWithDetailsDto : StudentDto
    {
        public GroupDto Group { get; set; }

    }
}
