//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace YC.EntityFrameworkCore
{
    public static class YCDbContextModelCreatingExtensions
    {
        public static void ConfigureYC(
            this ModelBuilder builder,
            Action<YCModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new YCModelBuilderConfigurationOptions();

            optionsAction?.Invoke(options);

            builder.ApplyConfiguration<YC.Students.Student>(new YC.Students.StudentConfiguration(options));
            builder.ApplyConfiguration<YC.Students.Group>(new YC.Students.GroupConfiguration(options));
        }
    }
}
